name: Build and Deploy

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # or your preferred version

      - name: Install dependencies
        run: |
          pip install Nikola
          pip install ruamel.yaml
          pip install ghp-import
          pip install pygal
          pip install micawber
          pip install jinja2

      - name: Build the site
        run: |
          nikola build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "jimcollinsworth@gmail.com"
          git config --global user.name "Jim Collinsworth"
          nikola github_deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}